### ISSUE TITLE
Add data value in mosaic

### ISSUE THREAD

**Issue by coulmont** [haleyjeppson/ggmosaic#6]
Hello. Sorry to bother you here. 
Is it possible to add data values (frequencies for example) in the mosaic
(example here http://stackoverflow.com/questions/6644997/showing-data-values-on-stacked-bar-chart-in-ggplot2 ) ?

**Comment by haleyjeppson** [comment]
Hi coulmont,

It is possible, though the answer is not as clean as the stackoverflow example. The issue is knowing where to place the labels on the plot. You can calculate the middle of each block by using the function `ggplot_build()` to extract a data frame containing the data used to render the plot. Using the example from stackoverflow, here is my solution for you:

```{r}
 Year      <- c(rep(c("2006-07", "2007-08", "2008-09", "2009-10"), each = 4))
 Category  <- c(rep(c("A", "B", "C", "D"), times = 4))
 Frequency <- c(168, 259, 226, 340, 216, 431, 319, 368, 423, 645, 234, 685, 166, 467, 274, 251)
 Data      <- data.frame(Year, Category, Frequency)

p <- ggplot(Data) + 
geom_mosaic(aes(weight=Frequency, x=product(Year), fill=Category)) + labs(x="Year", y="")

p +  geom_text(data = ggplot_build(p)$data[[1]], aes(x = (xmin+xmax)/2, y = (ymin+ymax)/2, label=.wt))
```

**Comment by coulmont** [comment]
Thanks ! I did not know about "ggplot_build(p)" !
